sebastienros/fluid

- Fluid.MvcSample/Views/Home/Index.liquid
- Fluid.MvcSample/Views/_ViewStart.liquid
- Fluid.MvcViewEngine/Statements/LayoutStatement.cs
- Fluid/Ast/IncludeStatement.cs
According to spec [here](https://help.shopify.com/themes/liquid/tags/theme-tags) it would be nice if we make the `.liquid` optional for both `include` and `layout` tags
> Make view extension optional

- Fluid.Tests/Fluid.Tests.csproj
- Fluid/Fluid.csproj
Hello:
I made a little modification to Support for .NET 4.6. 
All tests are passed successfully in both .NET Standard target and .NET 4.6 target.
Hope it helps.
> Add Support for .NET 4.6

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.Tests/TemplateTests.cs
- Fluid/Fluid.csproj
- Fluid/FluidTemplate.cs
Changed Irony to support custom cultures when parsing. Default culture is `InvariantCulture` which is the one used in Fluid.
Here is the corresponding change in Irony: https://github.com/sebastienros/irony/commit/4388b1fa9d79bb2d037ab6b7afd6b22fe4520aca
> Adding test to ensure parsed numbers are culture insensitive

- README.md
The syntax used in the example is not valid C#.
> Fixed typo in the Readme under "Intercepting a type access".

- Fluid.Tests/IncludeStatementTests.cs
- Fluid.Tests/Mocks/MockFileInfo.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/TemplateContext.cs
I believe this addresses the source of variables leaking into parent scope like in issue #45. This affects the `include` and `for` statements.
One thing I did was change TemplateContext.EnterChildScope from returning a `Scope` to returning `void`. This is because the TemplateContext.ReleaseScope method should be called and not the `Scope` object's `ReleaseScope`. I want to encourage callers to use TemplateContext's Release Scope method. Calling code can still technically call the Scope object's ReleaseScope method directly by accessing it via the TemplateContext.LocalScope property, but the result of doing so is undefined behavior.
This could be further refactored by introducing an interface that the Scope class would implement. The interface would not surface the `ReleaseScope` method. …
> Child and local scope handling by TemplateContext

- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/StringFilters.cs
The truncate filter errors if the input is nil or shorter than length. This fixes that.
> Truncate returns the input unmodified if the string is too short or nil

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
Fixes #52.
If returning NilValue is not correct (I guessed because I couldn't find any documentation), I can change it.
> First and Last now return NilValue when passed an empty array

- Fluid/MemberAccessStrategyExtensions.cs
Consider the following situation:
```csharp
class Test<T> { class Subclass { public int Someprop { get; set; } } }
...
context.MemberAccessStrategy.Register(typeof(Test<int>.Subclass));
context.MemberAccessStrategy.Register(typeof(Test<string>.Subclass));
```
If we add accessors for `Test<int>.Subclass.Someprop`
and `Test<string>.Subclass.Someprop`, both will have name
`Subclass-Someprop`, which will lead to runtime error
`System.Reflection.TargetException: Object does not match target type.`
Using Type.FullName could address this problem.
> Use `Type.FullName` instead of `Type.Name`.

- Fluid.Tests/ParserTests.cs
- Fluid/DefaultFluidParser.cs
- Fluid/ParserContext.cs
This throws an error if after parsing we are still in a block waiting for the end of it. Not sure if the terminology is what you would want with AreInBlock, maybe IsInBlock would be better, or just InBlock maybe. Feel free to change as needed. This will help my support people very much to have some idea what they did wrong.
> Add error handling for blocks.

- Fluid/Ast/FilterExpression.cs
I am trying to use Fluid to parse liquid templates and to extract translatable strings from them. 
`<span class="meta">{{ "Posted by" | t }}</span>`
Right now there isn't any way to find which filter is applied to a statement. This pull request makes the name of the filter and its parameters publicly accessible. It also makes `FilterExpression` class consistent with other classes in the `Ast` namespace, as they also use public properties instead of private fields to represent their state.
> Make Name and Parameter properties public in Ast.FilterExpression

- Fluid.MvcViewEngine/FluidRendering.cs
Somehow some [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) characters ended up in this line of code before each '.' character.  They interfere with some tooling.  This PR removes them.
> Remove zero-width space characters

- Fluid.Tests/NumberFiltersTests.cs
- Fluid/Filters/NumberFilters.cs
According to the [Liquid docs](https://help.shopify.com/en/themes/liquid/filters/math-filters), I think we missed the top 3 math filters: `abs`, `at_least` and `at_most`. This PR is to add them to the `NumberFilters`
> Add missing Math filters

- Fluid/MemberAccessStrategyExtensions.cs
There was still a problem with the registration. The generic version didn't do what API was promising. It was only adding the type. Now calling the non-generic version which also adds the members.
> Fix generic Register not registering members

- Fluid.Tests/ForStatementTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/DefaultFluidParser.cs
As discussed at https://github.com/OrchardCMS/OrchardCore/issues/5517 there was an issue with limit and offset no longer functioning. This corrects the issue and adds in unit tests.
> Fixed "limit" and "offset"; Added in Unit Tests

- Fluid.Tests/ForStatementTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/DefaultFluidParser.cs
Per https://shopify.github.io/liquid/tags/iteration/, the for statement can have an optional else clause that is executed in the case that the collection has no elements. This PR implements the else clause handling; it includes tests for both the parse and the for statement with else.
> Added else clause to for statement 

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
Usage of the '%l' date time filter causing errors:
e.g.
- 12:00 is parsed to 0:00
Suggested changes fix the issue with time from 24h to 12h format parsing.
> updated 12h time formatter

- Common.props
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.Tests/MemberAccessStrategyTests.cs
- Fluid/Fluid.csproj
- Fluid/MemberAccessStrategyExtensions.cs
- Fluid/Values/NilValue.cs
This PR addresses issue #135. When classes are registered, any property or field that is of type `Task<>` should be registered with an `AsyncDelegateAccessor` instead of a `DelegateAccessor` or `PropertyAccessor`. This could also be extended to `ValueTask<>` in future if desired.
This change uses reflection properties that are only available in netstandard2.0+, so support for netstandard1.6 was dropped. I'm sure there are other ways to achieve this support, but this seemed the most appropriate for future support while keeping the code simple.
It also relies on dynamic boxing of tasks to get the result without throwing cast exceptions, hence a dependency on `Microsoft.CSharp` was added.
> Correctly register async member accessors

- Fluid.Tests/NumberFiltersTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/DefaultFluidParser.cs
- Fluid/Filters/NumberFilters.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/BooleanValue.cs
- Fluid/Values/DateTimeValue.cs
- Fluid/Values/DictionaryValue.cs
- Fluid/Values/FactoryValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/NilValue.cs
- Fluid/Values/NumberValue.cs
- Fluid/Values/ObjectValue.cs
- Fluid/Values/StringValue.cs
The basic operations with decimal values using double as a base type causing calculation errors.
e.g. 
- 10.4 - 10 == 0.40000000000000036  
- 23.4-20 == 3.3999999999999986
Suggested changes of the base type from **double** to **decimal** avoid such calculation errors.
> changed number type to decimal, updated tests

- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/StringFilters.cs
Current implementation of slice filter throws an exception when any index is outside of string bounds. 
Proposed changes are fixing the issue by making the filter compliant with the Ruby implementation.
> slice filter is safe when indexes are outside bounds

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
BREAKING CHANGE %z previous included a colon in output, the docs for %z output '+0900'  , %:z will output '+09:00' (and also capital %Z)  which is the same output as %z did previously. This is to align with the docs for strftime (https://apidock.com/ruby/DateTime/strftime)
```
-  don't pad a numerical output.
_  use spaces for padding.
^  upcase the result string.
:  use colons for %z.
```
Not done (due to unable to find good examples of usage of '#', and that 0 padding appears to be a default?)
```
0  use zeros for padding.
```
> feat(DateFormat): Add flag parameters to date formats  fixes #14

- Fluid.Tests/BinaryExpressionTests.cs
- Fluid.Tests/Extensibility/ExtensibilityTests.cs
- Fluid.Tests/Extensibility/XorBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/EndsWithBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/StartsWithBinaryExpression.cs
- Fluid/FluidParser.cs
- README.md
Closes #197
Supports both string and array values.
Also changed the extensibility sample to another operator (exclusive or).
> Adds startswith/endswith operators

- Fluid.Tests/BinaryExpressionTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
- Fluid/Filters/StringFilters.cs
- Fluid/FluidParser.cs
- Fluid/TemplateContext.cs
- Fluid/Utils/StringBuilderPool.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/BlankValue.cs
- Fluid/Values/EmptyValue.cs
- Fluid/Values/FluidValues.cs
- Fluid/Values/NilValue.cs
- Fluid/Values/StringValue.cs
`empty` is now assumed equivalent to `'' and nil` meaning a variable that is either undefined (nil) or has an empty string will be equal to `empty`
> Fixing nil, blank, empty comparisons

- Fluid/Ast/IdentifierSegment.cs
- Fluid/Values/ObjectValue.cs
Spotted this while profiling NJsonSchema. Couple places where closure was created because context was unintentionally captured.
Before
```
|         Method |      Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|--------------- |----------:|---------:|---------:|--------:|-------:|------:|----------:|
|          Parse |  10.05 μs | 0.018 μs | 0.016 μs |  0.6256 |      - |     - |   2.59 KB |
|       ParseBig |  55.71 μs | 0.099 μs | 0.092 μs |  2.8076 | 0.0610 |     - |  11.63 KB |
|         Render | 786.13 μs | 2.105 μs | 1.969 μs | 39.0625 |      - |     - | 166.09 KB |
| ParseAndRender | 838.86 μs | 2.093 μs | 1.958 μs | 41.0156 | 9.7656 |     - |  168.8 KB |
```
After
```
|         Method |       Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Gen 2 | Allocated | …
```
> Make Awaited local methods static

- Fluid.Benchmarks/TagBenchmarks.cs
- Fluid/Ast/AssignStatement.cs
- Fluid/Ast/BinaryExpression.cs
- Fluid/Ast/BinaryExpressions/AndBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/OrBinaryExpression.cs
- Fluid/Ast/ElseIfStatement.cs
- Fluid/Ast/ElseStatement.cs
- Fluid/Ast/IfStatement.cs
- Fluid/Ast/IncrementStatement.cs
- Fluid/Ast/RawStatement.cs
- Fluid/Ast/TextSpanStatement.cs
- Fluid/ExceptionHelper.cs
- Fluid/TemplateContext.cs
- Fluid/TemplateOptions.cs
- Fluid/TrimmingFlags.cs
- Fluid/Utils/TaskExtensions.cs
Targeted the most obvious choices (often used or simple to change). If was the beast here and I'm sure the coded didn't get too clear by the change. Maybe judge that by the results - it's ugly but so often invoked...
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-6820HQ CPU 2.70GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.202
[Host]     : .NET Core 5.0.5 (CoreCLR 5.0.521.16609, CoreFX 5.0.521.16609), X64 RyuJIT
DefaultJob : .NET Core 5.0.5 (CoreCLR 5.0.521.16609, CoreFX 5.0.521.16609), X64 RyuJIT
```
| **Diff**|Method|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |RawTag_Parse|1,403.9 ns|12.71 ns|0.1125|0.0000|0.0000|472 B|
| **New** |	| **1,363.40 ns (-3%)** | **8.817 …
> Avoid state machines

- Fluid.Benchmarks/TagBenchmarks.cs
- Fluid/Ast/BinaryExpression.cs
- Fluid/Ast/BinaryExpressions/AddBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/AndBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/ContainsBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/DivideBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/EndsWithBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/EqualBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/GreaterThanBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/LowerThanExpression.cs
- Fluid/Ast/BinaryExpressions/ModuloBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/MultiplyBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/NotEqualBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/OrBinaryExpression.cs
- Fluid/Ast/BinaryExpressions/SubstractBinaryExpression.cs
- Fluid/FluidParserExtensions.cs
- Fluid/Values/FluidValue.cs
Spotted some things when profiling Orchard Agency, so let's work the magic.
* Use generic pattern in BinaryExpression to reduce state machines
* improve FluidValue conversion
* remove state machine in FluidParserExtensions
| **Diff**|Method|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |BinaryExpressions_Parse|10.022 μs|0.0235 μs|0.8392|0.0000|0.0000|3560 B|
| **New** |	| **9,969.8 ns (-3%)** | **32.87 ns** | **0.8392 (0%)** | **0.0000** | **0.0000** | **3560 B (0%)** |
| Old |BinaryExpressions_Render|1.352 μs|0.0032 μs|0.0134|0.0000|0.0000|56 B|
| **New** |	| **971.0 ns (-30%)** | **3.56 ns** | **0.0134 (0%)** | **0.0000** | **0.0000** | **56 B (0%)** |
> Reduce state machines in binary expressions

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
When an object is serialized with the json filter inaccessible member property names where still being written.
The values were always null, but I think the names of the properties should not be available either.
This just checks if it's a `NilValue` and skips writing the property name and value in that case.
> Hide json member names when not accessible

- Fluid.Tests/IncludeStatementTests.cs
- Fluid/Ast/IncludeStatement.cs
Simple but probably inefficient fix for the include statement not re-evaluating the Path which could be based on a MemberExpression that changes during a For...In loop.  Added unit test to demonstrate the problem, but feel additional tests involving a mock IFileProvider where we can test the number of times the file is resolved is required to prove that if the Path doesn't change the template is re-used and not reloaded.  I'm using the _identifier to compare the current path against the loaded path, again this could be better as I'm duplicating the "how to make an _identifier" logic, but I didn't want to change too much at this stage.  We could also reduce the amount of work to determine the path in the repeat cases, maybe even testing whether the path is a Literal or not.  I could have …
> IncludeStatement_ReevaluatePathOnEachWriteToAsync

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
Adds in a check for a cycle when writing json for an object.  Currently, a stack overflow exception is thrown.
The fix should allow multiple properties in the object graph to have the same references, it simply stops following a specific branch of the graph when a property value results in an object reference that has been traversed more than once already within the same graph path.
Fixes #351
> Prevent stack overflow in MiscFilters.WriteJson

- Fluid.Tests/MemberAccessStrategyTests.cs
- Fluid/MemberAccessStrategyExtensions.cs
NullReferenceException is thrown when the Model has a write-only property.
```
public class Test
{
public Int32 Id { protected get;set;}
}
```
> Skip write-only property

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
The nonparametric GetProperties() method returns the static properties together. If a custom MemberAccessStrategy is applied to an object, unexpected member names will be passed in. Therefore, JSON filters should skip these static properties.
> Json filter should skip static properties.

- Fluid.Tests/TemplateContextTests.cs
- Fluid/Scope.cs
- Fluid/TemplateContext.cs
> Fix NRE when setting null value in context

- Fluid.Tests/Extensibility/ExtensibilityTests.cs
- Fluid/FluidParser.cs
> Parse error when passing arguments to an empty tag.

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
> Implement allow_false argument for default filter

- Fluid.Tests/IncludeStatementTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/Ast/IncrementStatement.cs
- Fluid/Ast/RenderStatement.cs
- Fluid/FluidParser.cs
- Fluid/IsExternalInit.cs
- Fluid/Parser/ErrorMessages.cs
> Ensure the render tag is followed by a string

- Fluid.Tests/ParserTests.cs
- Fluid/FluidParser.cs
- Fluid/Parser/IdentifierParser.cs
> Identifiers can start with a digit

- Fluid.Tests/TemplateContextTests.cs
- Fluid/FluidTemplateExtensions.cs
> Fix async pattern in RenderAsync

- Fluid.Benchmarks/FluidValueBenchmarks.cs
- Fluid/Ast/LiquidStatement.cs
- Fluid/Values/FluidValue.cs
While doing performance checkup in Orchard (load test profiling agency theme) I noticed that there was quite big lock contention problem in Fluid, it originates from https://github.com/sebastienros/fluid/pull/387 where the logic never assigns anything on cache miss thus making the locking and looping happen every time for types like `ContentItem` (non-dictionary type). 
Fixed issue by using `Interlocked.CompareExchange`  (no locks needed) and also storing null as result for given type.  The dictionary was public, don't know why (Orchard doesn't seem to need it), made it private.
|         Method |     Mean |   Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------- |---------:|--------:|--------:|-------:|------:|------:|----------:|
| CreateFromList | 287.9 ns | 1.22 ns | …
> Fix lock contention in FluidValue.Create

- Fluid/Filters/MiscFilters.cs
- Fluid/Values/FluidValueExtensions.cs
I have a few custom filters in my solution for manipulating DateTime values and this would have been much easier if the TryGetDateTimeInput was made public or exposed.
I noticed there was another extension in this file and thought this would be a clean and simple approach that exposes this for custom filters in the Fluid.Filters namespace.
> Expose TryGetDateTimeInput to be usable by custom filters

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
I replaced the previous call to IMemberAccessor with GetValueAsync method
> Improve json filter

- Fluid.Tests/StringValueTests.cs
- Fluid/Values/StringValue.cs
Fixes #442
related to https://github.com/sebastienros/fluid/issues/234
> Fix NRE when creating null StringValue

- Fluid.Tests/ErrorMessagesTests.cs
- Fluid/FluidParserExtensions.cs
> Display source of error in message

- Fluid.MvcSample/CustomFluidViewParser.cs
- Fluid.MvcSample/Startup.cs
- Fluid.Tests/MvcViewEngine/SampleTests.cs
- Fluid.ViewEngine/FluidViewEngineOptions.cs
- Fluid.ViewEngine/FluidViewParser.cs
A small set of further changes to support the recent work allowing for FunctionValues. 
- Update to FluidViewParser constructor to pass FluidParserOptions argument  
- Update to sample projects to use the new constructor
> Allow FluidParserOptions to be configured using Fluid.MvcViewEngine

- README.md
Corrected MD syntax for the formatting of the numbered list and corrected namespace to add in the `using` statement
> Fixed formatting of bullet list in mvc section

- Fluid.Tests/ForStatementTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Ast/RangeExpression.cs
- Fluid/FluidParser.cs
> Implement offset continue

- Fluid.Tests/IfStatementTests.cs
- Fluid/Ast/IfStatement.cs
This code in awaited context check caused `elseIf.WriteToAsync` to always start writing, even when it should be only started if condition is true:
```c#
if (!elseIfConditionTask.IsCompletedSuccessfully)
{
var writeTask = elseIf.WriteToAsync(writer, encoder, context);
return AwaitedElseBranch(elseIfConditionTask, writeTask, writer, encoder, context, i + 1);
```
Parametrized test case to test async and non-async paths the get some red tests and then fixed. Now passing the `elseIf` and write task is retrieved, if needed.
We found out this when running on Linux against sync code, which was quite curious, on Windows it always worked.
> Fix ElseIfStatement double-evaluation in awaited context

- Fluid.Tests/ColorFiltersTests.cs
- Fluid/Filters/ColorFilters.cs
I actually wanted to fix a different bug regarding layout file resolution, but all color tests were failing on my german Windows machine so this had to come first. 
Color filters need to generate and parse valid CSS values. The syntax of
these is always independent of the currently set culture, so the filters
must reflect that by using CultureInfo.InvariantCulture.
The Visual Studio auto formatter also changed stuff like 
```
if ((uint) red > 255)
```
to
```
if ((uint)red > 255)
```
There seems to be no `.editorconfig` in this repository so I don't know if this is right 🤷‍♂️. If you don't want this, I will change it back :).
> Make color filter independent of CultureInfo.CurrentCulture

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/MemberAccessStrategyExtensions.cs
- Fluid/Values/FluidValue.cs
> Add support for TimeSpan

- Fluid.Tests/ColorFiltersTests.cs
- Fluid.Tests/Extensions/ConversionExtensions.cs
- Fluid.Tests/Integration/StandardFilterTests.cs
- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/StringFilters.cs
Bonus - add a missing assert statement in `RemovesReturnsInputWhenArgumentIsEmpty` unit test.
Resolve #494
> Add replace_last and remove_last filters

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.Tests/Fluid.Tests.csproj
- README.md
> Bump packages

- .github/workflows/build.yml
- Fluid.Tests/Fluid.Tests.csproj
- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Values/FluidValueExtensions.cs
- README.md
> Fix TimeZone parsing

- Fluid/Ast/ForStatement.cs
- Fluid/Scope.cs
> Expose own properties of scopes publicly

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.MinimalApisSample/Fluid.MinimalApisSample.csproj
- Fluid.MvcSample/Fluid.MvcSample.csproj
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.Tests/Fluid.Tests.csproj
- Fluid.ViewEngine/Fluid.ViewEngine.csproj
- Fluid/Fluid.csproj
- MinimalApis.LiquidViews/MinimalApis.LiquidViews.csproj
Time to let go of `netoreapp3.1` and `net5.0`. `net7.0` will be obsolete soon too but left it. To sweeten the deal here are the benchmark numbers comparing jump from NET 7.0 to NET 8.0. And then for vanity comparison benchmarks under net8.0
```
BenchmarkDotNet v0.13.10, Windows 11 (10.0.23590.1000)
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 8.0.100
[Host]     : .NET 7.0.14 (7.0.1423.51910), X64 RyuJIT AVX2
Job-PXTLYP : .NET 7.0.14 (7.0.1423.51910), X64 RyuJIT AVX2
Job-ZZEUIR : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
```
| Method         | Runtime  | Mean       | Error     | StdDev    | Ratio | Gen0   | Gen1   | Allocated | Alloc Ratio |
|--------------- |--------- |-----------:|----------:|----------:|------:|-------:|-------:|----------:|------------:|
| Parse …
> Add net8.0 target, remove obsolete, update packages

- Fluid/Properties/AssemblyInfo.cs
Let's extract some free perf with the magic attribute. Fluid doesn't expect specific initialization and usages should be safe. Same thing is used in Parlot, Esprima and Jint.
| **Diff**|Method|Toolchain|Mean|Error|Allocated|
|------- |-------|-------|-------:|-------|-------:|
| Old |Parse|Default|4.455 μs|0.0235 μs|2.68 KB|
| **New** |	| **Default** | **4.345 μs (-2%)** | **0.0164 μs** | **2.68 KB (0%)** |
| Old |ParseBig|Default|23.970 μs|0.1198 μs|11.61 KB|
| **New** |	| **Default** | **23.470 μs (-2%)** | **0.0663 μs** | **11.61 KB (0%)** |
| Old |Render|Default|189.348 μs|0.6141 μs|95.86 KB|
| **New** |	| **Default** | **191.471 μs (+1%)** | **0.7625 μs** | **95.86 KB (0%)** |
| Old |ParseAndRender|Default|200.195 μs|0.4416 μs|99.01 KB|
| **New** |	| **Default** | **197.654 μs …
> Add module level SkipLocalsInit

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
- README.md
Added "Sum" ArrayFilter so that others can use it also.
2 options:
- Can include an argument to indicate which member to Sum on an array of objects
- No argument which will attempt to Sum the array items value
Tests included with Pull Request which check both of these scenario's
We use Fluid quite a lot at TemplateTo and hope you don't mind us putting our link in your UsedBy section, Fluid can be used by our users as well when building out their templates.
> Added Sum ArrayFilter with 2 different options

- Fluid/Ast/ForStatement.cs
- Fluid/Ast/TextSpanStatement.cs
- Fluid/Values/FluidValues.cs
- Fluid/Values/FunctionValue.cs
Extracted from the compilation branch
> Improve TextSpan and For statements

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
Corrects where to follow the `where` documentation from liquid language repository.  Additionally, it deals with a case where the comparison value is actually false, which would lead to the comparison being performed with a true value.
Corrects #620
> Adjust Where filter to properly handle truthy comparisons.

- Common.props
The file is being stamped as 2.0.0 and I think this causes Wix installer to skip applying updates, seen this before. 
https://nuget.info/packages/Fluid.Core/2.12.0
After removing the property I get local build using a fictional 2.3.4 version parameter (like in publish GH workflow):
Might be the source of [#5035](https://github.com/RicoSuter/NSwag/issues/5035)
> Remove explicit FileVersion configuration

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid.Tests/AssignmentCaptureTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/AssignStatement.cs
- Fluid/Ast/CaptureStatement.cs
- Fluid/TemplateContext.cs
- Fluid/TemplateOptions.cs
- Fluid/Values/StringValue.cs
Allows the execution of a C# delegate whenever values are assigned via an `assign` or `capture` tag.
> Assigned delegate

- Fluid.Tests/ParserTests.cs
- Fluid/Parser/TagParsers.cs
> Fix end tag detection in liquid tag

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
- Fluid/TemplateOptions.cs
- README.md
> Add JavaScriptEncoder option

- Fluid.Tests/VisitorTest.cs
- Fluid.Tests/Visitors/ParserVisitor.cs
- Fluid/Ast/AstRewriter.cs
- Fluid/Ast/AstVisitor.cs
- Fluid/FluidParser.cs
- Fluid/Parser/EmptyBlockStatement.cs
- Fluid/Parser/EmptyTagStatement.cs
- Fluid/Parser/ParserBlockStatement.cs
- Fluid/Parser/ParserTagStatement.cs
- README.md
> Add custom statements visitor support

- Fluid.Tests/StringValueTests.cs
- Fluid/Values/StringValue.cs
> Fix `StringValue.Create` encode overload.

- Directory.Packages.props
- Fluid.Tests/ParserTests.cs
- Fluid/FluidParser.cs
- Fluid/FluidParserOptions.cs
- Fluid/Parser/TagParsers.cs
- README.md
- Versions.props
- global.json
Fixes https://github.com/sebastienros/fluid/issues/687
Fixes https://github.com/sebastienros/fluid/issues/768
> Make liquid tag optional to improve parsing performance

- Directory.Packages.props
- Fluid.Tests/TemplateTests.cs
- Fluid/Fluid.csproj
- Fluid/MemberNameStrategies.cs
- Fluid/TemplateOptions.cs
- Versions.props
Use LTS version (8.0.5) when the dependency is required: 
- netstandard2.0 required the STJ package
- net6.0 doesn't have `JsonNamingPolicy` so the package is referenced
> Fix System.Text.Json versions

- Fluid.Benchmarks/BaseBenchmarks.cs
- Fluid.Benchmarks/ComparisonBenchmarks.cs
- Fluid.Benchmarks/CompiledFluidBenchmarks.cs
- Fluid.Benchmarks/DotLiquidBenchmarks.cs
- Fluid.Benchmarks/FluidBenchmarks.cs
- Fluid.Benchmarks/HandlebarsBenchmarks.cs
- Fluid.Benchmarks/LiquidNetBenchmarks.cs
- Fluid.Benchmarks/Program.cs
- Fluid.Benchmarks/ScribanBenchmarks.cs
- Fluid.Benchmarks/product.mustache
Was wondering how this benchmark would not allocate as much as the others. It's actually not doing the same thing. The `{{#truncate}}` is not a thing unless implemented specifically.
Also changing the size of the list so the end result isn't too big. Will update the benchmark results in the other PR that has the charts.
> Fix Handlebars benchmarks

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
c.f. https://github.com/Shopify/liquid/issues/1849
> Add `find`, `find_index`, `has` and `reject` filters

- Fluid/Values/FluidValue.cs
To my understanding, these ad hoc conversions required when doing interop between model and the template so these a transient and will not need to later reflect any state changes done in models. In NSwag there are properties that return empty enumerables with dynamic LINQ where outcome is an empty enumerator 90% of the cases.
> Avoid creating empty ArrayValue instances

- Fluid/UnsafeMemberAccessStrategy.cs
`UnsafeMemberAccessStrategy` will always call Register again if member was not found. It's enough to have invalid reference in Liquid template for this endless re-registration to kick in.
> Avoid re-registration if member not found in UnsafeMemberAccessStrategy

- Fluid/Ast/TextSpanStatement.cs
- Fluid/DefaultMemberAccessStrategy.cs
- Fluid/Shims.cs
It's wasteful do do a doble lookup to get onto type's member level. Now using single key. Added also simple `Lock` shim for non NET  9 targets.
> Use single dictionary in DefaultMemberAccessStrategy

- Fluid/Ast/MemberExpression.cs
- Fluid/ExceptionHelper.cs
* use array without IReadOnlyList dispatch cost
> Improve MemberExpression performance

- Fluid/DefaultMemberAccessStrategy.cs
As star is used for custom accessors, it's not that common. Now keeping track if such has been registered to any type and then only creating new key and doing the second dictionary lookup.
> Avoid cost of star member access lookup if not registered

- Fluid/Accessors/PropertyInfoAccessor.cs
* special case common bool and int property access
* use abstract class instead of interface do reduce virtual dispatch cost
When profiling NJsonSchema, found out that now after optimizations almost 10% of allocations originate from boolean value boxing (very common in code generation templates).
> Reduce value type boxing in interop calls

- Fluid.Tests/ParserTests.cs
- Fluid/Ast/LiquidStatement.cs
> Fix liquid tag completions support

- .github/workflows/build.yml
- .github/workflows/pr.yml
- .github/workflows/publish.yml
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.Tests/Fluid.Tests.csproj
- Fluid.ViewEngine/Fluid.ViewEngine.csproj
- Fluid/Fluid.csproj
- Versions.props
It's been obsolete a long time and possible core library users will just fall back to netstandard2.0. NET 6.0 has been flagged as unsupported target in newer runtime libs and causes warnings when used.
> Drop obsolete .NET 6.0 support

- Directory.Packages.props
- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Fluid.csproj
- Fluid/Shims.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/DictionaryValue.cs
Currently Uniq filter doesn't work for arrays containing dictionaries or other arrays. This PR adds support for this by implementing GetHashCode in ArrayValue and DictionaryValue.
> Implemented GetHashCode in ArrayValue.cs and DictionaryValue.cs
