sebastienros/fluid

- Fluid.MvcSample/Fluid.MvcSample.csproj
The project sample working fine from the CLI, nothing but when I try to debug it from the VS it shows an error message
After modifying the .csproj you will be able to do both ways
> Fix Fluid.MvcSample debug issue in VS 15.3.0 Preview 2.0

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.Benchmarks/FluidBenchmarks.cs
I've added Liquid.NET library to benchmarks comparison. 
Liquid.NET does not support netcore1.1. I've upgraded Fluid.Benchmarks.csproj to netcore2
I also updated the DotLiquid to the latest version
> Added Liquid.NET benchmarks.

- Fluid.MvcSample/Views/Home/Index.liquid
- Fluid.MvcSample/Views/Home/_Partial.liquid
- Fluid.MvcSample/Views/_Layout.liquid
- Fluid.MvcSample/Views/_Partial.liquid
- Fluid.MvcViewEngine/FluidRendering.cs
- Fluid.Tests/IncludeStatementTests.cs
- Fluid/Ast/IncludeStatement.cs
#28 
I registered the ambient values locally. I wasn't sure how to do it globally.
> Render include file contents

- Fluid.MvcViewEngine/FluidRendering.cs
- Fluid/Ast/IncludeStatement.cs
> Remove dead FluidTemplateFactory property

- Fluid.Tests/ParserTests.cs
- Fluid/DefaultFluidParser.cs
> Ignore tags in raw and comment blocks

- Fluid.Tests/IncludeStatementTests.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/DefaultFluidParser.cs
- Fluid/FluidGrammar.cs
> Support inline variable assignment in Include tag

- Fluid.Tests/IncludeStatementTests.cs
- Fluid.Tests/Mocks/MockFileInfo.cs
- Fluid.Tests/Mocks/MockFileProvider.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/DefaultFluidParser.cs
- Fluid/FluidGrammar.cs
This a second part of the issue #30
> Add 'with' option to Include tag

- Fluid.Tests/ForStatementTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Scope.cs
> Removing child scope in For loops

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
Fixes https://github.com/OrchardCMS/OrchardCore/issues/1397
> Implement sort filter on properties

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/StringFilters.cs
> Add ellipsis to Truncate & TruncateWords

- Fluid.Tests/Domain/Content.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Accessors/AsyncDelegateAccessor.cs
- Fluid/Accessors/AsyncDelegateAccessorOfT.cs
- Fluid/Accessors/DelegateAccessor.cs
- Fluid/Accessors/DelegateAccessorOfT.cs
- Fluid/Ast/IdentifierSegment.cs
- Fluid/Ast/IndexerSegment.cs
- Fluid/Filters/ArrayFilters.cs
- Fluid/IMemberAccessor.cs
- Fluid/MemberAccessStrategyExtensions.cs
- Fluid/TemplateContext.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/DictionaryValue.cs
- Fluid/Values/FactoryValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/ObjectValue.cs
- Fluid/Values/StringValue.cs
`Register` accepts `async` methods
`SetValue` accepts factories to delay the value instantiation
/cc @paynecrl97
> Adding async and lazy initialization support

- Fluid.Tests/ParserTests.cs
- Fluid/DefaultFluidParser.cs
> Fix incorrect position in parser error messages

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.Tests/MemberAccessStrategyTests.cs
- Fluid.Tests/TemplateTests.cs
> fix all the warnings when build

- Fluid.MvcViewEngine/Tags/LayoutTag.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/DefaultFluidParser.cs
Hungarian suck, `"endz".StartsWith("end")` is `false`
> Using culture insensitive comparisons

- Fluid/Pooling.cs
The version brought from Jint was stripped from Interlocked usage, need to add the unmodified Roslyn's version that works reliably concurrently.
> Use ObjectPool with Interlocked

- Fluid.Tests/NumberFiltersTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/DefaultFluidParser.cs
- Fluid/Filters/NumberFilters.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/NumberValue.cs
> Fixing integral numbers support

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
Fixes #72
Also adding sort_natural filter
> Fixing sort filter

- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid/Fluid.csproj
> Targeting netstandard2.0

- Fluid.Tests/TemplateTests.cs
- Fluid/FluidTemplateExtensions.cs
- README.md
> Use no encoder by default

- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.Benchmarks/FluidBenchmarks.cs
- Fluid.Tests/TemplateContextTests.cs
- Fluid/Accessors/DelegateAccessorOfT.cs
- Fluid/Accessors/PropertyInfoAccessor.cs
- Fluid/MemberAccessStrategy.cs
- Fluid/MemberAccessStrategyExtensions.cs
>  Fix concurrent registration of type members

- Fluid.Tests/TemplateTests.cs
- Fluid/Filters/ArrayFilters.cs
add where filter to array FilterCollection and tests. 
related issue #121
> add process where filter tests

- Fluid.Tests/ForStatementTests.cs
- Fluid/Ast/ForStatement.cs
> Fix zero based loop issue

- Fluid/BaseFluidTemplate.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/BooleanValue.cs
- Fluid/Values/DateTimeValue.cs
- Fluid/Values/FactoryValue.cs
- Fluid/Values/NumberValue.cs
- Fluid/Values/ObjectValue.cs
- Fluid/Values/StringValue.cs
> Avoid NullReferenceException in FluidValue implementations

- Fluid.Tests/StringFiltersTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Filters/StringFilters.cs
Add strip_newlines filter  (https://shopify.github.io/liquid/filters/strip_newlines/)    #153
> feat (strip_newlines filter): Add strip_newlines filter

- Fluid.Tests/TemplateTests.cs
- Fluid/ConcurrentMemberAccessStrategy.cs
- Fluid/IMemberAccessStrategy.cs
- Fluid/MemberAccessStrategy.cs
> Add option for ignore member casing

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
> Fixing NRE in where clause

- Fluid.Tests/ForStatementTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/DefaultFluidParser.cs
> Accepting variables in for loop options

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid.Tests/BinaryExpressionTests.cs
- Fluid.Tests/NumberFiltersTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/DefaultFluidParser.cs
- Fluid/Filters/ArrayFilters.cs
- Fluid/Filters/NumberFilters.cs
- Fluid/FluidGrammar.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/NumberValue.cs
- Fluid/Values/StringValue.cs
Since we are using `decimal` that can retain the integral scale.
> Remove integral flags

- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/CaptureStatement.cs
- README.md
> Don't encore captures

- Fluid/DefaultFluidParser.cs
- Fluid/Fluid.csproj
- Fluid/MemberAccessStrategyExtensions.cs
- Fluid/Tags/ITag.cs
I haven't updated any missing documentation, just tweaked the existing to compile correctly.
> Generate xml documentation

- Fluid.Tests/ParserTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/TemplateContext.cs
- README.md
> Add model to TemplateContext constructor

- Fluid.Tests/ColorFiltersTests.cs
- Fluid/Filters/ColorFilters.cs
- Fluid/TemplateContext.cs
> Add color_to_rgb filter

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
> strinp_html returns empty if input is null/empty

- Fluid.MvcSample/CustomFluidViewParser.cs
- Fluid.MvcSample/Startup.cs
- Fluid.MvcViewEngine/FluidRendering.cs
- Fluid.MvcViewEngine/FluidViewEngine.cs
- Fluid.MvcViewEngine/FluidViewEngineOptions.cs
- Fluid.MvcViewEngine/FluidViewParser.cs
- Fluid/Ast/IncludeStatement.cs
- README.md
> Fixing MVC view engine

- Fluid.Tests/UnlessStatementTests.cs
- Fluid/Ast/UnlessStatement.cs
- Fluid/FluidParser.cs
> Add else statement in unless tag

- Fluid.Tests/TemplateContextTests.cs
- Fluid/Ast/IdentifierSegment.cs
> Allow to render different models

- Fluid/Scope.cs
> Expose scope properties names

- Fluid.Tests/Extensibility/ExtensibilityTests.cs
- Fluid.Tests/ForStatementTests.cs
- Fluid.Tests/MiscFiltersTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/Ast/BreakStatement.cs
- Fluid/Ast/CommentStatement.cs
- Fluid/Ast/ContinueStatement.cs
- Fluid/Ast/DecrementStatement.cs
- Fluid/Ast/IncrementStatement.cs
- Fluid/Ast/LiteralExpression.cs
- Fluid/Ast/RawStatement.cs
- Fluid/Ast/Statement.cs
- Fluid/Ast/TextSpanStatement.cs
- Fluid/FluidParser.cs
> Allow primary expression in for tags

- Fluid.Tests/CycleStatementTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/FluidParser.cs
> Fixing cycle tag

- .github/workflows/build.yml
- .github/workflows/publish.yml
- Fluid.MvcSample/CustomFluidViewParser.cs
- Fluid.MvcSample/Startup.cs
- Fluid.MvcViewEngine/Directory.Build.props
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.MvcViewEngine/FluidRendering.cs
- Fluid.MvcViewEngine/FluidViewEngine.cs
- Fluid.MvcViewEngine/FluidViewEngineOptionsSetup.cs
- Fluid.MvcViewEngine/MvcViewFeaturesMvcBuilderExtensions.cs
- Fluid.Tests/MvcViewEngine/MvcViewEngineTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid.ViewEngine/Constants.cs
- Fluid.ViewEngine/Directory.Build.props
- Fluid.ViewEngine/FileProviderMapper.cs
- Fluid.ViewEngine/Fluid.ViewEngine.csproj
- Fluid.ViewEngine/FluidViewEngineOptions.cs
- Fluid.ViewEngine/FluidViewParser.cs
- Fluid.ViewEngine/FluidViewRenderer.cs
- Fluid.ViewEngine/IFluidViewRenderer.cs
- Fluid.sln
- Fluid/Ast/IncludeStatement.cs
- Fluid/Ast/TextSpanStatement.cs
- Fluid/IFluidTemplate.cs
- Fluid/Parser/CompositeFluidTemplate.cs
- Fluid/Parser/FluidTemplate.cs
- Fluid/TemplateOptions.cs
- Fluid/UnsafeMemberAccessStrategy.cs
- Async io compatible statements
- Fixes {% include %} fixes cache #36
- Use 6.0 preview sdk for builds
> Reusable Fluid.ViewEngine package

- Fluid.Tests/StringValueTests.cs
- Fluid/Values/StringValue.cs
> StringValue can be initialized with null

- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/RawStatement.cs
> Fix raw statement

- Fluid.Tests/ParserTests.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/BlankValue.cs
- Fluid/Values/BooleanValue.cs
- Fluid/Values/DictionaryValue.cs
- Fluid/Values/EmptyValue.cs
- Fluid/Values/NumberValue.cs
- Fluid/Values/StringValue.cs
> Fix comparisons with empty and blank

- Fluid.Tests/BinaryExpressionTests.cs
- Fluid/FluidParser.cs
> Fix logical condition tree building

- Fluid.Tests/ErrorMessagesTests.cs
- Fluid.Tests/Extensibility/ExtensibilityTests.cs
- Fluid.Tests/MvcViewEngine/MvcViewEngineTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/FluidParser.cs
- Fluid/Parser/ErrorMessages.cs
> Render error messages

- Fluid.Tests/TemplateContextTests.cs
- Fluid/Ast/IdentifierSegment.cs
> Fix accessor cache

- Fluid.Tests/Domain/Person.cs
- Fluid.Tests/MemberAccessStrategyTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/IdentifierSegment.cs
- Fluid/Ast/MemberSegment.cs
- Fluid/TemplateContext.cs
- README.md
> Add AllowModelMembers option

- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/IdentifierSegment.cs
- Fluid/DefaultMemberAccessStrategy.cs
- Fluid/MemberAccessStrategyExtensions.cs
- Fluid/MemberNameStrategies.cs
- Fluid/UnsafeMemberAccessStrategy.cs
> Fix custom casing in unsafe access

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
> Fix default filter behavior

- Fluid.Benchmarks/BaseBenchmarks.cs
- Fluid.Benchmarks/ComparisonBenchmarks.cs
- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.Benchmarks/HandlebarsBenchmarks.cs
- Fluid.Benchmarks/product.mustache
- Fluid/Scope.cs
- Fluid/TemplateContext.cs
- Fluid/TemplateOptions.cs
- README.md
> Add Handlebars benchmarks

- Fluid.Tests/ParserTests.cs
- Fluid/Parser/TagParsers.cs
> Fix whitespace in output tags

- Fluid.Tests/ParserTests.cs
- Fluid/FluidParser.cs
> Fix ambiguous identifiers

- Fluid/Filters/StringFilters.cs
`removefirst` -> `remove_first`
`replacefirst` -> `replace_first`
> Fix filter names

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid.Tests/MiscFiltersTests.cs
- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
- Fluid/Filters/MiscFilters.cs
- Fluid/Filters/StringFilters.cs
> Fix 'reverse' naming collision

- Fluid.Tests/IncludeStatementTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/FluidParser.cs
- Fluid/Scope.cs
- Fluid/TemplateContext.cs
- Fluid/Values/ForLoopValue.cs
> Add render tag

- Fluid.Tests/TemplateTests.cs
- Fluid/Filters/ArrayFilters.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/StringValue.cs
> Use GetValueAsync when evaluating first, last and size filters

- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Scope.cs
- Fluid/TemplateContext.cs
- Fluid/Values/StringValue.cs
> Fix for loop scopes

- Fluid.Tests/FunctionTests.cs
- Fluid.Tests/ParserTests.cs
- Fluid/Ast/FilterExpression.cs
- Fluid/Ast/FunctionCallArgument.cs
- Fluid/Ast/FunctionCallSegment.cs
- Fluid/Ast/MacroStatement.cs
- Fluid/Fluid.csproj
- Fluid/FluidParser.cs
- Fluid/FluidParserOptions.cs
- Fluid/FunctionArguments.cs
- Fluid/Parser/ErrorMessages.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/FunctionValue.cs
- README.md
> Implement functions

- Fluid.Tests/TemplateTests.cs
> Fix IgnoreCasing test

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid.Tests/Domain/WithInterfaces/PetValue.cs
- Fluid.Tests/MiscFiltersTests.cs
- Fluid.Tests/StringFiltersTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/Ast/RenderStatement.cs
- Fluid/Filters/ArrayFilters.cs
- Fluid/Filters/MiscFilters.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/DictionaryValue.cs
- Fluid/Values/FactoryValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/StringValue.cs
Fixes #447
Fixes #446
I believe some iterations can now use the Awaited pattern.
> Make Enumerate asynchronous

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid.Tests/CaseStatementTests.cs
- Fluid.Tests/ColorFiltersTests.cs
- Fluid.Tests/CycleStatementTests.cs
- Fluid.Tests/FunctionTests.cs
- Fluid.Tests/IncludeStatementTests.cs
- Fluid.Tests/MiscFiltersTests.cs
- Fluid.Tests/StringFiltersTests.cs
- Fluid.Tests/StringValueTests.cs
- Fluid.Tests/TemplateContextTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Ast/BinaryExpressions/AddBinaryExpression.cs
- Fluid/Ast/CaptureStatement.cs
- Fluid/Ast/MacroStatement.cs
- Fluid/Filters/ArrayFilters.cs
- Fluid/Filters/ColorFilters.cs
- Fluid/Filters/MiscFilters.cs
- Fluid/Filters/StringFilters.cs
- Fluid/FluidParser.cs
- Fluid/TemplateContext.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/DateTimeValue.cs
- Fluid/Values/DictionaryValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/StringValue.cs
- README.md
> Remove constructors from common Fluid values

- Fluid.MvcViewEngine/FluidMvcViewOptions.cs
- Fluid.MvcViewEngine/FluidViewEngineOptionsSetup.cs
- Fluid.Tests/Mocks/MockFileProvider.cs
- Fluid.Tests/MvcViewEngine/ViewEngineTests.cs
- Fluid.ViewEngine/FluidViewEngineOptions.cs
- Fluid.ViewEngine/FluidViewParser.cs
- Fluid.ViewEngine/FluidViewRenderer.cs
- MinimalApis.LiquidViews/FluidViewEngineOptionsSetup.cs
- README.md
> Fix layout discovery

- MinimalApis.LiquidViews/ActionViewResult.cs
> Use configured TemplateOptions for ActionViewResult.ExecuteAsync()

- .github/workflows/build.yml
- Fluid.MvcViewEngine/FluidMvcViewOptions.cs
- Fluid.MvcViewEngine/FluidRendering.cs
- Fluid.MvcViewEngine/FluidTagHelper.cs
- Fluid.MvcViewEngine/FluidView.cs
- Fluid.Tests/MvcViewEngine/ViewEngineTests.cs
- Fluid.ViewEngine/FluidViewEngineOptions.cs
- Fluid.ViewEngine/FluidViewRenderer.cs
> Add rendering event

- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/StringFilters.cs
> Don't add ellipsis when size is greater than number of words

- Fluid.Tests/CaseStatementTests.cs
- Fluid/Ast/CaseStatement.cs
- Fluid/FluidParser.cs
> Fix case/when tag multi-statements evaluation

- Fluid.Tests/TemplateTests.cs
- Fluid/Values/StringValue.cs
> String indexer should return nil

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
> Implement missing strftime formats

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
Fixes https://github.com/sebastienros/fluid/issues/544
> Introduce "local" time zone for time_zone filter 

- Fluid.Tests/ArrayFiltersTests.cs
- Fluid/Filters/ArrayFilters.cs
> Concatenate arrays with single elements

- Fluid.Tests/BinaryExpressionTests.cs
- Fluid.Tests/TemplateTests.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/DictionaryValue.cs
> Fix Array and Dictionary equality checks

- Fluid.ViewEngine/FluidViewRenderer.cs
> Allow Synchronous operations in FluidViewRenderer

- Fluid/Ast/FunctionCallSegment.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/Ast/RangeExpression.cs
- Fluid/Ast/RenderStatement.cs
- Fluid/DefaultMemberAccessStrategy.cs
- Fluid/ExceptionHelper.cs
- Fluid/Filters/ColorFilters.cs
- Fluid/Filters/MiscFilters.cs
- Fluid/Filters/StringFilters.cs
- Fluid/Fluid.csproj
- Fluid/IsExternalInit.cs
- Fluid/MemberNameStrategies.cs
- Fluid/NullMemberAccessor.cs
- Fluid/Parser/ErrorMessages.cs
- Fluid/Shims.cs
- Fluid/TemplateContext.cs
- Fluid/Utils/ObjectPool.cs
- Fluid/Values/ArrayValue.cs
- Fluid/Values/BlankValue.cs
- Fluid/Values/BooleanValue.cs
- Fluid/Values/DateTimeValue.cs
- Fluid/Values/DictionaryValue.cs
- Fluid/Values/EmptyValue.cs
- Fluid/Values/FluidValue.cs
- Fluid/Values/FluidValueDictionaryFluidIndexable.cs
- Fluid/Values/FunctionValue.cs
- Fluid/Values/NilValue.cs
- Fluid/Values/NumberValue.cs
- Fluid/Values/ObjectValueBase.cs
- Fluid/Values/StringValue.cs
* ignore non-critical ones for now
> Enable latest-Recommended analyzers and fix issues

- .github/workflows/build.yml
- .github/workflows/publish.yml
> Ensure deterministic build for release

- README.md
Add a note in the README about accessing the cst.
Fixes #482.
> Add documentation about accessing the CST

- .github/workflows/build.yml
- .github/workflows/pr.yml
- .github/workflows/publish.yml
- Common.props
Noticed that the DLL has 0.0.0.0 as version.
> Add file version information and use latest actions/checkout

- Fluid/Fluid.csproj
https://www.nuget.org/packages/Parlot/0.0.25
> Update Parlot 0.0.25

- Fluid.Tests/StringFiltersTests.cs
- Fluid/Filters/StringFilters.cs
Fixes https://github.com/sebastienros/fluid/issues/635
> Fix slice out of range errors

- Directory.Packages.props
- Fluid.Benchmarks/Fluid.Benchmarks.csproj
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.Tests/Fluid.Tests.csproj
- Fluid.Tests/GlobalSuppressions.cs
- Fluid.sln
- Fluid/Fluid.csproj
- MinimalApis.LiquidViews/MinimalApis.LiquidViews.csproj
Fixes https://github.com/sebastienros/fluid/issues/638
> Use central package management

- Directory.Packages.props
- Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj
- Fluid.Tests/Fluid.Tests.csproj
- Fluid/Fluid.csproj
https://github.com/sebastienros/fluid/issues/646
> fix: Directory.Packages.props does not respect PrivateAssets property

- README.md
Mailgen:
A Node.js package that generates clean, responsive HTML e-mails for sending transactional mail.
> Update README.md: Add Mailgen to the list of projects using Fluid

- Fluid.Tests/ForStatementTests.cs
- Fluid.Tests/IncludeStatementTests.cs
- Fluid/Ast/ForStatement.cs
- Fluid/Ast/IncludeStatement.cs
- Fluid/Ast/RenderStatement.cs
> Fix swapped rindex and rindex0 in 'for', 'include' and 'render'

- Fluid.Tests/TemplateTests.cs
- Fluid/FluidParser.cs
> Add support for numerical properties

- Directory.Packages.props
- Fluid.Tests/Domain/CustomStruct.cs
- Fluid.Tests/MemberAccessStrategyTests.cs
- Fluid/Accessors/PropertyInfoAccessor.cs
- Fluid/Fluid.csproj
> Add direct support for structs

- Fluid/Parser/ErrorMessages.cs
Addresses https://github.com/sebastienros/fluid/pull/755#issuecomment-2652723564
> Obsolete ParentesesAfterFunctionName

- Directory.Packages.props
https://github.com/sebastienros/parlot/releases/tag/v1.3.3
> Upgrade to Parlot 1.3.3

- Fluid.Tests/MiscFiltersTests.cs
- Fluid/Filters/MiscFilters.cs
Add HMAC Filters similar to https://shopify.dev/docs/api/liquid/filters/hmac_sha1
> Add HMAC Filters

- Directory.Packages.props
- Versions.props
Reverts sebastienros/fluid#792
> Revert "Bump the all-dependencies group with 2 updates"

- .github/workflows/build.yml
- .github/workflows/pr.yml
- Directory.Packages.props
- Fluid.Tests/Fluid.Tests.csproj
Now we have beautiful test summaries and PR creators can see a more detailed test problem and even navigate to it: https://github.com/sebastienros/fluid/actions/runs/15093294077?pr=800
> Add GitHubActionsTestLogger

- Directory.Packages.props
- Versions.props
Reverts sebastienros/fluid#806
> Revert changes on abstractions
